- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure webfilter profile in FortiGate
    fortios_webfilter:
      host:  "{{  host }}"
      username: "{{  username}}"
      password: "{{ password }}"
      vdom:  "{{  vdom }}"
      webfilter_profile:
        name: "default"
        state: "present"
        replacemsg-group: "myreplacementgroup"
        inspection-mode: "flow-based"
        options: "cookiefilter"
        https-replacemsg: "enable"
        ovrd-perm: "urlfilter-override"
        post-action: "normal"
        override:
          ovrd-cookie: "deny"
          ovrd-scope: "user"
          profile-type: "list"
          ovrd-dur-mode: "constant"
          ovrd-dur: "15m"
          profile-attribute: "Login-LAT-Service"
          ovrd-user-group: []
          profile": []
        web:
          urlfilter-table: "1"
          content-header-list: "2"
          blacklist: "disable"
          whitelist: "exempt-av"
          safe-search: ""
          youtube-restrict: "none"
          log-search: "disable"
          keyword-match: []
        ftgd-wf:
          options: "ftgd-disable"
          category-override: "\n"
          exempt-quota: "17"
          ovrd: "\n"
          filters:
            - id: 1
              q_origin_key: 1
              category: 2
              action: "block"
              warn-duration: "5m"
              auth-usr-grp: []
              log: "enable"
              override-replacemsg: ""
              warning-prompt: "per-category"
              warning-duration-type: "timeout"
            - id: 2
              q_origin_key: 2
              category: 7
              action: "block"
              warn-duration: "5m"
              auth-usr-grp: []
              log: "enable"
              override-replacemsg: ""
              warning-prompt: "per-category"
              warning-duration-type: "timeout"
          quota: []
          max-quota-timeout: 300
          rate-image-urls: "enable"
          rate-javascript-urls": "enable"
          rate-css-urls: "enable"
          rate-crl-urls: "enable"
        wisp: "disable"
        wisp-servers: []
        wisp-algorithm: "auto-learning"
        log-all-url: "disable"
        web-content-log: "enable"
        web-filter-activex-log: "enable"
        web-filter-command-block-log: "enable"
        web-filter-cookie-log: "enable"
        web-filter-applet-log: "enable"
        web-filter-jscript-log: "enable"
        web-filter-js-log: "disable"
        web-filter-vbs-log: "enable"
        web-filter-unknown-log: "enable"
        web-filter-referer-log: "enable"
        web-filter-cookie-removal-log: "enable"
        web-url-log: "enable"
        web-invalid-domain-log: "enable"
        web-ftgd-err-log: "enable"
        web-ftgd-quota-usage: "enable"