- hosts: localhost
  vars:
    host: "192.168.122.12"
    username: "admin"
    password: ""
  tasks:
  - name: Change max message size in domain (needs dsa.com domain created)
    fortimailconfig:
      action: "put"
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      domain: "dsa.com"
      data:
        "objectID": "DomainSetting:{D:dsa.com}"
        "mdomain": "dsa.com"
        "max_msg_size": "10800"

