- hosts: localhost
  tasks:
  - name: Upload license
    fortiosconfig:
     config: "system vmlicense upload"
     action: "upload"
     host:  "192.168.122.40"
     username: "admin"
     password: ""
     vdom:  "global"
     https: False
     config_parameters:
      filename: "license_file.lic"
  - name: Upload license second fortigate
    fortiosconfig:
     config: "system vmlicense upload"
     action: "upload"
     host:  "192.168.122.41"
     username: "admin"
     password: ""
     vdom:  "global"
     https: False
     config_parameters:
      filename: "license_file2.lic"
