- hosts: localhost
  vars:
    host: "192.168.122.12"
    username: "admin"
    password: ""
  tasks:
  - name: Get domain
    fortimailconfig:
      action: "get"
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      domain: "dsa.com"
