- hosts: localhost
  vars:
    host: "192.168.122.50"
    username: "admin"
    password: ""
  tasks:
  - name: Get system info
    fortimailconfig:
      action: "get"
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      resource: "SysStatusSysinfo"
