- hosts: localhost
#  strategy: debug
  vars:
   host: "192.168.122.70"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: pass cli cmd ssh
    fortiosconfig:
     action: "ssh"
     host:  "{{  host }}"  
     username: "{{  username}}"  
     password: "{{ password }}"  
     commands: |
               execute update-now
               get system status
               